- name: Add customer alpha (Nokia models) 
  netconf_config:
    datastore: candidate
    content: |
        <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
          <configure xmlns="urn:nokia.com:sros:ns:yang:sr:conf">
            <service>
              <customer operation="create">
                <customer-name>alpha</customer-name>
                <customer-id>10</customer-id>
              </customer>
            </service>
          </configure>
        </config>

